---
title: "Netcdf"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ncdf4)
library(ggplot2)
library(dplyr)
library(tidyr)
```

# Read in netcdf

```{r}
nc <- nc_open("arctic-training/data/WG2013CTD.nc")
```


```{r}
#print(nc)

vars <- attributes(nc$var)$names
vars

dims <- attributes(nc$dim)$names
dims

salinity <- ncvar_get(nc,"sal")
time <- ncvar_get(nc,"time")
depth <- ncvar_get(nc,"z")

time <- as.POSIXct((time + 719529)*86400, origin = "1970-01-01", tz = "UTC")

salinity_data <- as.data.frame(salinity)
```

# Reformat the output

Assign comum names, reshape data

```{r}
names(salinity_data) <- as.character(depth)

salinity_data_long <- salinity_data %>% 
  mutate(time = time) %>% 
  gather(key="depth", value = "salinity", -time) %>% 
  mutate(depth = as.numeric(depth))
```


# Make the plots

```{r}
ggplot(salinity_data_long, aes(x = time, y = depth, fill = salinity)) +
    geom_raster()
```

```{r}
ggplot(salinity_data_long, aes(x = salinity,
                          y = depth,
                          group = time,
                          color = time)) +
    geom_line(size = .1) +
    scale_y_reverse()
```
